### ISSUE TITLE
Allow customization of head node resources

### ISSUE THREAD

**Issue by multimeric** [aws/amazon-genomics-cli#213]
[//]: #  (Before raising the feature request, please check to see if an existing feature request already exists.)

**Description**

Allow the user to define system resources for the head node of the workflow, which will then be mapped to an appropriate instance in the selected context

**Use Case**

My nextflow pipeline consists of many hundreds of thousands of processes. When I run it, the `agc` selects the smallest node available (in my context, this is a 2 CPU, 4 GB RAM instance). This is not suitable in this case. I get the following error:

```
Wed, 08 Dec 2021 23:09:13 +1100	org.codehaus.groovy.runtime.InvokerInvocationException: java.lang.OutOfMemoryError: Java heap space
Wed, 08 Dec 2021 23:09:13 +1100		at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:113)
Wed, 08 Dec 2021 23:09:13 +1100		at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
Wed, 08 Dec 2021 23:09:13 +1100		at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1268)
Wed, 08 Dec 2021 23:09:13 +1100		at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035)
Wed, 08 Dec 2021 23:09:13 +1100		at org.codehaus.groovy.runtime.InvokerHelper.invokePojoMethod(InvokerHelper.java:1017)
Wed, 08 Dec 2021 23:09:13 +1100		at org.codehaus.groovy.runtime.InvokerHelper.invokeMethod(InvokerHelper.java:1008)
Wed, 08 Dec 2021 23:09:13 +1100		at groovyx.gpars.actor.Actor.callDynamic(Actor.java:368)
Wed, 08 Dec 2021 23:09:13 +1100		at groovyx.gpars.actor.Actor.handleException(Actor.java:339)
Wed, 08 Dec 2021 23:09:13 +1100		at groovyx.gpars.actor.AbstractLoopingActor$1.registerError(AbstractLoopingActor.java:63)
Wed, 08 Dec 2021 23:09:13 +1100		at groovyx.gpars.util.AsyncMessagingCore.run(AsyncMessagingCore.java:140)
Wed, 08 Dec 2021 23:09:13 +1100		at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
Wed, 08 Dec 2021 23:09:13 +1100		at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
Wed, 08 Dec 2021 23:09:13 +1100		at java.base/java.lang.Thread.run(Thread.java:829)
Wed, 08 Dec 2021 23:09:13 +1100	Caused by: java.lang.OutOfMemoryError: Java heap space
Wed, 08 Dec 2021 23:09:38 +1100	Execution aborted due to an unexpected error
Wed, 08 Dec 2021 23:10:03 +1100	Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "Actor Thread 698"
Wed, 08 Dec 2021 23:10:14 +1100	Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "java-sdk-http-connection-reaper"
Wed, 08 Dec 2021 23:10:50 +1100	Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "AWSBatch-executor-457"
Wed, 08 Dec 2021 23:11:04 +1100	Execution aborted due to an unexpected error
```

**Proposed Solution**

Allow the addition of system resources to the `engine` key of the `context`:
```yaml
contexts:
  someCtx:
    engines:
      - type: wdl
        engine: cromwell
        mem: 16GB
```

or

```yaml
contexts:
  someCtx:
    engines:
      - type: wdl
        engine: cromwell
        instanceType: c5.2xlarge
```

**Comment by multimeric** [comment]
Ah, turns out this is a duplicate of #204.

**Comment by multimeric** [comment]
In the short term, if anyone comes here from the future, look into this hack: https://github.com/aws/amazon-genomics-cli/issues/204#issuecomment-989328995
