### ISSUE TITLE
Rnaseq workflow in nf-core-project example no longer works

### ISSUE THREAD

**Issue by tneely** [aws/amazon-genomics-cli#246]
[//]: #  (Please do not include your AWS account or credentials as part of the bug request.)

**Describe the Bug**

[//]: #  (Please describe the behavior that you are seeing with as many details as possible including logs from AGC, CloudWatch snippets and CloudFormation errors if relevant.)
It appears the rnaseq project was updated recently to require a new version of Nextflow than what we use, causing it to fail when run.

https://github.com/nf-core/rnaseq/releases/tag/3.5

**Steps to Reproduce**

[//]: #  (Include a list of steps that can be used to reproduce the bug.)
1. Deploy the `bigMemCtx` in the example project and run `agc workflow run rnaseq -c bigMemCtx`
2. Run `agc workflow status` and confirm the workflow failed

**Relevant Logs**

[//]: #  (The logs that where obtained by running the commands here. Please run the command with "-v" so that we can see the verbose logs.)

```
nextflow.exception.AbortOperationException: Nextflow version 21.04.3 does not match workflow required version: >=21.10.3
--
at nextflow.Session.showVersionError(Session.groovy:819)
at nextflow.Session.checkVersion(Session.groovy:814)
at nextflow.Session.validate(Session.groovy:786)
at nextflow.Session.notifyBeforeWorkflowExecution(Session.groovy:1004)
at nextflow.Session$notifyBeforeWorkflowExecution$0.call(Unknown Source)
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:130)
at nextflow.script.BaseScript.runDsl2(BaseScript.groovy:190)
at nextflow.script.BaseScript.run(BaseScript.groovy:200)
at nextflow.script.ScriptParser.runScript(ScriptParser.groovy:221)
at nextflow.script.ScriptRunner.run(ScriptRunner.groovy:212)
at nextflow.script.ScriptRunner.execute(ScriptRunner.groovy:120)
at nextflow.cli.CmdRun.run(CmdRun.groovy:302)
at nextflow.cli.Launcher.run(Launcher.groovy:475)
at nextflow.cli.Launcher.main(Launcher.groovy:657)
```

**Expected Behavior**

[//]: #  (A clear and concise description of what you expected to happen.)
The workflow succeeds.

**Actual Behavior**

[//]: #  (A clear and concise description of what actually happened.)
The workflow fails.

**Additional Context**

Operating System: macOS
AGC Version: 1.1.2
Was AGC setup with a custom bucket: No
Was AGC setup with a custom VPC: No

**Comment by tneely** [comment]
We will most likely want to update the nextflow engine on next release. For backwards compatibility though, I wonder if we can pin the example to a specific version/commit?
