### ISSUE TITLE
AGC run command failures with 500 and 504 errors

### ISSUE THREAD

**Issue by amdixit** [aws/amazon-genomics-cli#513]
[//]: #  (Please do not include your AWS account or credentials as part of the bug request.)

**Describe the Bug**

[//]: #  (Please describe the behavior that you are seeing with as many details as possible including logs from AGC, CloudWatch snippets and CloudFormation errors if relevant.)

**Steps to Reproduce**

[//]: #  (Include a list of steps that can be used to reproduce the bug.)

**Relevant Logs**

[//]: #  (The logs that where obtained by running the commands here. Please run the command with "-v" so that we can see the verbose logs.)

**Expected Behavior**
I expect to run without errors
agc workflow run <process> --context <name> --format json

**Actual Behavior**

I am submitting several hundred requests in a loop and I see a handful of them successful but after about 30 submissions the command throws a combination of 504 and 500 errors, Below is an example:
 error="unable to run workflow: 504 Gateway Timeout"

I also noticed that the target group attached to the loadbalancer that power some of the apis has unhealthy target and it cycles through them quickly. When I checked the logs of the target, I see the below failures:

2022-09-02 14:55:28,971 WARN - data commit logging failed org.hsqldb.HsqlException: file input/output error: cromwell-executions/cromwell-db/cromwell-db.log at org.hsqldb.error.Error.error(Unknown Source) at org.hsqldb.error.Error.error(Unknown Source) at org.hsqldb.scriptio.ScriptWriterText.writeRowOutToFile(Unknown Source) at org.hsqldb.scriptio.ScriptWriterText.writeSequenceStatement(Unknown Source) at org.hsqldb.persist.Log.writeSequenceStatement(Unknown Source) at org.hsqldb.persist.Logger.writeSequenceStatement(Unknown Source) at org.hsqldb.Session.logSequences(Unknown Source) at org.hsqldb.TransactionManagerCommon.persistCommit(Unknown Source) at org.hsqldb.TransactionManagerMVCC.commitTransaction(Unknown Source) at org.hsqldb.Session.commit(Unknown Source) at org.hsqldb.Session.executeCompiledStatement(Unknown Source) at org.hsqldb.persist.LobManager.createFullBlockAddresses(Unknown Source) at org.hsqldb.persist.LobManager.setBytesBACompressedPart(Unknown Source) at org.hsqldb.persist.LobManager.setBytesISCompressed(Unknown Source) at org.hsqldb.persist.LobManager.setBytesIS(Unknown Source) at org.hsqldb.persist.LobManager.setCharsForNewClob(Unknown Source) at org.hsqldb.SessionData.allocateLobForResult(Unknown Source) at org.hsqldb.Session.allocateResultLob(Unknown Source) at org.hsqldb.jdbc.JDBCPreparedStatement.performPreExecute(Unknown Source) at org.hsqldb.jdbc.JDBCPreparedStatement.addBatch(Unknown Source) at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.addBatch(HikariProxyPreparedStatement.java) at slick.jdbc.JdbcActionComponent$InsertActionComposerImpl$MultiInsertAction.$anonfun$run$19(JdbcActionComponent.scala:540) at slick.jdbc.JdbcActionComponent$InsertActionComposerImpl$MultiInsertAction.$anonfun$run$19$adapted(JdbcActionComponent.scala:538) at scala.collection.immutable.List.foreach(List.scala:431) at slick.jdbc.JdbcActionComponent$InsertActionComposerImpl$MultiInsertAction.$anonfun$run$18(JdbcActionComponent.scala:538) at slick.jdbc.JdbcBackend$SessionDef.withPreparedStatement(JdbcBackend.scala:425) at slick.jdbc.JdbcBackend$SessionDef.withPreparedStatement$(JdbcBackend.scala:420) at slick.jdbc.JdbcBackend$BaseSession.withPreparedStatement(JdbcBackend.scala:489) at slick.jdbc.JdbcActionComponent$InsertActionComposerImpl.preparedInsert(JdbcActionComponent.scala:511) at slick.jdbc.JdbcActionComponent$InsertActionComposerImpl$MultiInsertAction.run(JdbcActionComponent.scala:536) at slick.jdbc.JdbcActionComponent$SimpleJdbcProfileAction.run(JdbcActionComponent.scala:28) at slick.jdbc.JdbcActionComponent$SimpleJdbcProfileAction.run(JdbcActionComponent.scala:25) at slick.dbio.DBIOAction$$anon$1.$anonfun$run$1(DBIOAction.scala:186) at scala.collection.Iterator.foreach(Iterator.scala:943) at scala.collection.Iterator.foreach$(Iterator.scala:943) at scala.collection.AbstractIterator.foreach(Iterator.scala:1431) at scala.collection.IterableLike.foreach(IterableLike.scala:74) at scala.collection.IterableLike.foreach$(IterableLike.scala:73) at scala.collection.AbstractIterable.foreach(Iterable.scala:56) at slick.dbio.DBIOAction$$anon$1.run(DBIOAction.scala:186) at slick.dbio.DBIOAction$$anon$1.run(DBIOAction.scala:183) at slick.basic.BasicBackend$DatabaseDef$$anon$3.liftedTree1$1(BasicBackend.scala:276) at slick.basic.BasicBackend$DatabaseDef$$anon$3.run(BasicBackend.scala:276) at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) at java.base/java.lang.Thread.run(Thread.java:829)

**Screenshots**

[//]: #  (If applicable, add screenshots to help explain your problem.)

**Additional Context**

If I create a new context and submit additional jobs it works for a handful requests and then failure reoccurs. I have scaled the ecs tasks to a higher number + increased EFS throughput, yet no luck.

There seems to be a bottleneck somewhere and I can't seem to place it.

[//]: #  (Add any other context about the problem here. The minimum required information is below)

Operating System:
AGC Version: 1.5.0
Was AGC setup with a custom bucket: No
Was AGC setup with a custom VPC: No

**Comment by markjschreiber** [comment]
When scripting against AGC I would recommend including pauses with sleep statements to ensure the backend infrastructure doesn't start throttling requests.

From the stack trace it appears that you are using Cromwell and the error it is experiencing is in communicating with it's metadata database. This could also be due to attempting to start many workflows quickly.

AGC Contexts based on Cromwell have one cromwell server per context which manages all workflows submitted. It may be that attempting to manage 30+ concurrently is beyond it's capacity. A possible alternative would be to use the miniwdl engine in the context. In this situation each workflow spawns it's own engine task. However, you will still be sharing some key infrastructure in the context so overloading can still be a problem.

Deploying multiple contexts would be another mechanism to spread the load.

**Comment by amdixit** [comment]
Why deploying multiple tasks (Cromwell engine service tasks) per context not be an option?

**Comment by markjschreiber** [comment]
You can run multiple tasks but at some point you will start to overload the Cromwell server. The number you can run will depend somewhat on how many tasks the workflow has to keep track of. Workflows with large scatter steps will put a larger burden on the server.
