### ISSUE TITLE
ecr:SetRepositoryPolicy missing for account activate with minimum permissions

### ISSUE THREAD

**Issue by ArlindNocaj** [aws/amazon-genomics-cli#573]
[//]: #  (Please do not include your AWS account or credentials as part of the bug request.)

**Describe the Bug**
agc account activate not working due to missing permissions of admin policy described in https://aws.github.io/amazon-genomics-cli/docs/best-practices/iampermissions/

[//]: #  (Please describe the behavior that you are seeing with as many details as possible including logs from AGC, CloudWatch snippets and CloudFormation errors if relevant.)

**Steps to Reproduce**

[//]: #  (Include a list of steps that can be used to reproduce the bug.)

**Relevant Logs**

[//]: #  (The logs that where obtained by running the commands here. Please run the command with "-v" so that we can see the verbose logs.)
Admin:~/environment $ agc account activate
2022-11-22T08:44:50Z 𝒊  Activating AGC with bucket '' and VPC ''
Bootstrapping CDK... [-o--] 51s                                                                                                                                                                    2022-11-22T08:45:41Z ✘  [WARNING] aws-cdk-lib.aws_ssm.StringParameterProps#type is deprecated.
2022-11-22T08:45:41Z ✘    - type will always be 'String'
2022-11-22T08:45:41Z ✘    This API will be removed in the next major release.
2022-11-22T08:45:41Z ✘  [WARNING] aws-cdk-lib.aws_ssm.ParameterType is deprecated.
2022-11-22T08:45:41Z ✘    these types are no longer used
2022-11-22T08:45:41Z ✘    This API will be removed in the next major release.
2022-11-22T08:45:41Z ✘  [WARNING] aws-cdk-lib.aws_ssm.ParameterType#STRING is deprecated.
2022-11-22T08:45:41Z ✘    
2022-11-22T08:45:41Z ✘    This API will be removed in the next major release.
2022-11-22T08:45:41Z ✘  current credentials could not be used to assume 'arn:aws:iam::287209812789:role/cdk-agc-lookup-role-287209812789-us-east-1', but are for the right account. Proceeding anyway.
2022-11-22T08:45:41Z ✘  [WARNING] aws-cdk-lib.aws_ssm.StringParameterProps#type is deprecated.
2022-11-22T08:45:41Z ✘    - type will always be 'String'
2022-11-22T08:45:41Z ✘    This API will be removed in the next major release.
2022-11-22T08:45:41Z ✘  [WARNING] aws-cdk-lib.aws_ssm.ParameterType is deprecated.
2022-11-22T08:45:41Z ✘    these types are no longer used
2022-11-22T08:45:41Z ✘    This API will be removed in the next major release.
2022-11-22T08:45:41Z ✘  [WARNING] aws-cdk-lib.aws_ssm.ParameterType#STRING is deprecated.
2022-11-22T08:45:41Z ✘    
2022-11-22T08:45:41Z ✘    This API will be removed in the next major release.
2022-11-22T08:45:41Z ✘   ⏳  Bootstrapping environment aws://287209812789/us-east-1...
2022-11-22T08:45:41Z ✘  Using default execution policy of 'arn:aws:iam::aws:policy/AdministratorAccess'. Pass '--cloudformation-execution-policies' to customize.
2022-11-22T08:45:41Z ✘  Agc-CDKToolkit: creating CloudFormation changeset...
2022-11-22T08:45:41Z ✘  Agc-CDKToolkit |  0/12 | 8:45:12 AM | REVIEW_IN_PROGRESS   | AWS::CloudFormation::Stack | Agc-CDKToolkit User Initiated
2022-11-22T08:45:41Z ✘  Agc-CDKToolkit |  0/12 | 8:45:18 AM | CREATE_IN_PROGRESS   | AWS::CloudFormation::Stack | Agc-CDKToolkit User Initiated
2022-11-22T08:45:41Z ✘  Agc-CDKToolkit |  0/12 | 8:45:23 AM | CREATE_IN_PROGRESS   | AWS::ECR::Repository  | ContainerAssetsRepository 
2022-11-22T08:45:41Z ✘  Agc-CDKToolkit |  0/12 | 8:45:23 AM | CREATE_IN_PROGRESS   | AWS::IAM::Role        | CloudFormationExecutionRole 
2022-11-22T08:45:41Z ✘  Agc-CDKToolkit |  0/12 | 8:45:23 AM | CREATE_IN_PROGRESS   | AWS::SSM::Parameter   | CdkBootstrapVersion 
2022-11-22T08:45:41Z ✘  Agc-CDKToolkit |  0/12 | 8:45:23 AM | CREATE_IN_PROGRESS   | AWS::IAM::Role        | ImagePublishingRole 
2022-11-22T08:45:41Z ✘  Agc-CDKToolkit |  0/12 | 8:45:23 AM | CREATE_IN_PROGRESS   | AWS::IAM::Role        | LookupRole 
2022-11-22T08:45:41Z ✘  Agc-CDKToolkit |  0/12 | 8:45:24 AM | CREATE_IN_PROGRESS   | AWS::IAM::Role        | FilePublishingRole 
2022-11-22T08:45:41Z ✘  Agc-CDKToolkit |  0/12 | 8:45:24 AM | CREATE_IN_PROGRESS   | AWS::S3::Bucket       | StagingBucket 
2022-11-22T08:45:41Z ✘  Agc-CDKToolkit |  0/12 | 8:45:24 AM | CREATE_IN_PROGRESS   | AWS::IAM::Role        | CloudFormationExecutionRole Resource creation Initiated
2022-11-22T08:45:41Z ✘  Agc-CDKToolkit |  0/12 | 8:45:24 AM | CREATE_IN_PROGRESS   | AWS::IAM::Role        | ImagePublishingRole Resource creation Initiated
2022-11-22T08:45:41Z ✘  Agc-CDKToolkit |  0/12 | 8:45:24 AM | CREATE_FAILED        | AWS::S3::Bucket       | StagingBucket cdk-agc-assets-287209812789-us-east-1 already exists
2022-11-22T08:45:41Z ✘  Agc-CDKToolkit |  0/12 | 8:45:24 AM | CREATE_IN_PROGRESS   | AWS::IAM::Role        | LookupRole Resource creation Initiated
2022-11-22T08:45:41Z ✘  Agc-CDKToolkit |  0/12 | 8:45:24 AM | CREATE_IN_PROGRESS   | AWS::IAM::Role        | FilePublishingRole Resource creation Initiated
2022-11-22T08:45:41Z ✘  Agc-CDKToolkit |  0/12 | 8:45:25 AM | CREATE_FAILED        | AWS::IAM::Role        | ImagePublishingRole Resource creation cancelled
2022-11-22T08:45:41Z ✘  Agc-CDKToolkit |  0/12 | 8:45:25 AM | CREATE_FAILED        | AWS::IAM::Role        | CloudFormationExecutionRole Resource creation cancelled
2022-11-22T08:45:41Z ✘  Agc-CDKToolkit |  0/12 | 8:45:25 AM | CREATE_FAILED        | AWS::IAM::Role        | FilePublishingRole Resource creation cancelled
2022-11-22T08:45:41Z ✘  Agc-CDKToolkit |  0/12 | 8:45:25 AM | CREATE_FAILED        | AWS::IAM::Role        | LookupRole Resource creation cancelled
2022-11-22T08:45:41Z ✘  Agc-CDKToolkit |  0/12 | 8:45:25 AM | CREATE_FAILED        | AWS::SSM::Parameter   | CdkBootstrapVersion Resource creation cancelled
2022-11-22T08:45:41Z ✘  Agc-CDKToolkit |  0/12 | 8:45:25 AM | CREATE_FAILED        | AWS::ECR::Repository  | ContainerAssetsRepository Resource creation cancelled
2022-11-22T08:45:41Z ✘  Agc-CDKToolkit |  0/12 | 8:45:26 AM | ROLLBACK_IN_PROGRESS | AWS::CloudFormation::Stack | Agc-CDKToolkit The following resource(s) failed to create: [ImagePublishingRole, FilePublishingRole, CdkBootstrapVersion, LookupRole, StagingBucket, CloudFormationExecutionRole, ContainerAssetsRepository]. Rollback requested by user.
2022-11-22T08:45:41Z ✘  Agc-CDKToolkit |  0/12 | 8:45:34 AM | DELETE_IN_PROGRESS   | AWS::IAM::Role        | ImagePublishingRole 
2022-11-22T08:45:41Z ✘  Agc-CDKToolkit |  0/12 | 8:45:34 AM | DELETE_IN_PROGRESS   | AWS::IAM::Role        | LookupRole 
2022-11-22T08:45:41Z ✘  Agc-CDKToolkit |  0/12 | 8:45:34 AM | DELETE_SKIPPED       | AWS::S3::Bucket       | StagingBucket 
2022-11-22T08:45:41Z ✘  Agc-CDKToolkit |  0/12 | 8:45:34 AM | DELETE_IN_PROGRESS   | AWS::IAM::Role        | CloudFormationExecutionRole 
2022-11-22T08:45:41Z ✘  Agc-CDKToolkit |  0/12 | 8:45:34 AM | DELETE_IN_PROGRESS   | AWS::IAM::Role        | FilePublishingRole 
2022-11-22T08:45:41Z ✘  Agc-CDKToolkit |  1/12 | 8:45:34 AM | DELETE_COMPLETE      | AWS::ECR::Repository  | ContainerAssetsRepository 
2022-11-22T08:45:41Z ✘  Agc-CDKToolkit |  2/12 | 8:45:35 AM | DELETE_COMPLETE      | AWS::SSM::Parameter   | CdkBootstrapVersion 
2022-11-22T08:45:41Z ✘  Agc-CDKToolkit |  3/12 | 8:45:36 AM | DELETE_COMPLETE      | AWS::IAM::Role        | ImagePublishingRole 
2022-11-22T08:45:41Z ✘  Agc-CDKToolkit |  4/12 | 8:45:36 AM | DELETE_COMPLETE      | AWS::IAM::Role        | FilePublishingRole 
2022-11-22T08:45:41Z ✘  Agc-CDKToolkit |  5/12 | 8:45:36 AM | DELETE_COMPLETE      | AWS::IAM::Role        | LookupRole 
2022-11-22T08:45:41Z ✘  Agc-CDKToolkit |  6/12 | 8:45:36 AM | DELETE_COMPLETE      | AWS::IAM::Role        | CloudFormationExecutionRole 
2022-11-22T08:45:41Z ✘  Agc-CDKToolkit |  7/12 | 8:45:37 AM | ROLLBACK_COMPLETE    | AWS::CloudFormation::Stack | Agc-CDKToolkit 
2022-11-22T08:45:41Z ✘  
2022-11-22T08:45:41Z ✘  Failed resources:
2022-11-22T08:45:41Z ✘  Agc-CDKToolkit | 8:45:24 AM | CREATE_FAILED        | AWS::S3::Bucket       | StagingBucket cdk-agc-assets-287209812789-us-east-1 already exists
2022-11-22T08:45:41Z ✘   ❌  Environment aws://287209812789/us-east-1 failed bootstrapping: Error: The stack named Agc-CDKToolkit failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE: cdk-agc-assets-287209812789-us-east-1 already exists
2022-11-22T08:45:41Z ✘      at FullCloudFormationDeployment.monitorDeployment (/home/ec2-user/.agc/cdk/node_modules/aws-cdk/lib/api/deploy-stack.ts:496:13)
2022-11-22T08:45:41Z ✘      at processTicksAndRejections (node:internal/process/task_queues:96:5)
2022-11-22T08:45:41Z ✘      at /home/ec2-user/.agc/cdk/node_modules/aws-cdk/lib/cdk-toolkit.ts:626:24
2022-11-22T08:45:41Z ✘      at async Promise.all (index 0)
2022-11-22T08:45:41Z ✘      at CdkToolkit.bootstrap (/home/ec2-user/.agc/cdk/node_modules/aws-cdk/lib/cdk-toolkit.ts:623:5)
2022-11-22T08:45:41Z ✘      at initCommandLine (/home/ec2-user/.agc/cdk/node_modules/aws-cdk/lib/cli.ts:357:12)
2022-11-22T08:45:41Z ✘  
2022-11-22T08:45:41Z ✘  The stack named Agc-CDKToolkit failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE: cdk-agc-assets-287209812789-us-east-1 already exists
2022-11-22T08:45:41Z ✘   error="exit status 1"

**Expected Behavior**

[//]: #  (A clear and concise description of what you expected to happen.)

**Actual Behavior**

[//]: #  (A clear and concise description of what actually happened.)

**Screenshots**

[//]: #  (If applicable, add screenshots to help explain your problem.)

**Additional Context**

[//]: #  (Add any other context about the problem here. The minimum required information is below)

Operating System:
AGC Version:
Was AGC setup with a custom bucket:
Was AGC setup with a custom VPC:

**Comment by vvalleru** [comment]
Because the previous deployment/cleanup failed unsuccessfully. You need to delete this manually first before attempting to deploy it again.
