### ISSUE TITLE
Add support for S3 server-side-encrypted-KMS (SSE-KMS)

### ISSUE THREAD

**Issue by ArlindNocaj** [aws/amazon-genomics-cli#87]
[//]: #  (Before raising the feature request, please check to see if an existing feature request already exists.)

**Description**

AGC cannot be used if server-side-encryption with KMS is being used in the aws account.

Steps to reproduce:

* perform cdk bootstrap -> `BucketA` (generates cdk s3 bootstrap bucket)
* create your data bucket: e.g. `s3://hidden95` -> `BucketB`
* add bucket policy enforcing kms encryption on upload of content. AWS recommended way to enforce SSE KMS encryption on upload
```
{
    "Version": "2012-10-17",
    "Id": "PutObjPolicy",
    "Statement": [
        {
            "Sid": "DenyIncorrectEncryptionHeader",
            "Effect": "Deny",
            "Principal": "*",
            "Action": "s3:PutObject",
            "Resource": "arn:aws:s3:::hidden95/*",
            "Condition": {
                "StringNotEquals": {
                    "s3:x-amz-server-side-encryption": "aws:kms"
                }
            }
        },
        {
            "Sid": "DenyUnEncryptedObjectUploads",
            "Effect": "Deny",
            "Principal": "*",
            "Action": "s3:PutObject",
            "Resource": "arn:aws:s3:::hidden95/*",
            "Condition": {
                "Null": {
                    "s3:x-amz-server-side-encryption": "true"
                }
            }
        }
    ]
}
```
* `agc account activate --bucket hidden95`
* `agc context deploy --context spotContext`

Result: agc fails, since it cannot upload to the S3 bucket without adding sse-kms to the upload.

**Use Case**

Large companies often use S3 bucket policies to prevent upload of unencrypted objects to S3, as suggested in [amazon recommend sse-kms](https://aws.amazon.com/blogs/security/how-to-prevent-uploads-of-unencrypted-objects-to-amazon-s3/)

This means that AGC in its current state cannot be used by these companies.

**Proposed Solution**

Suggested by @elliot-smith 
To enable SSE-KMS, AGC will need the following modifications:

* The AGC command to upload S3 assets will need to optionally supply the required "x-amz-server-side-encryption" header
* The Batch instances will need to have the "kms:Decrypt" IAM property so that the key can be decrypted before it is downloaded
* The documentation will need to be updated to specify this and most likely call out that enabling this functionally requires additional minimum IAM policies

**Other information**

[//]: #  (detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. associated pull-request, stackoverflow, slack, etc)

**Comment by ArlindNocaj** [comment]
@wleepang I fixed this problem directly in CDK, see [CDK SSE fix](https://github.com/aws/aws-cdk/pull/17668).

Can you please update to use CDK 1 or 2 with latest release which contains the above fix?
This fix makes sure that cdk sends the encryption header based on the default encryption defined in the S3 bucket.

` 
2021-12-15T09:58:17+01:00 ✘  Agc-Context-NextflowDemo-myuser4nFMjG-spotContext: deploying...
2021-12-15T09:58:17+01:00 ✘  [0%] start: Publishing 2efbb30cc14169c0e67fb1c1121827636cb27fd11c749a27671bde3ee1a28ef6:current
2021-12-15T09:58:17+01:00 ✘  [25%] fail: Access Denied
2021-12-15T09:58:17+01:00 ✘  [25%] start: Publishing 54aa9368cb0af77728b139df544966eb0ee9754a76a567e67d1db78a861cdb72:current
2021-12-15T09:58:17+01:00 ✘  [50%] fail: Access Denied
2021-12-15T09:58:17+01:00 ✘  [50%] start: Publishing 8a44a9ffd1e7ff8112f4efad90e4916da815d54408f1e8709a55508e447a241b:current
2021-12-15T09:58:17+01:00 ✘  [75%] fail: Access Denied
2021-12-15T09:58:17+01:00 ✘  [75%] start: Publishing cc44eb3674174e873dbbcd74d711c6746c069b4e29f5346eeecb401bcad4f59d:current
2021-12-15T09:58:17+01:00 ✘  [100%] fail: Access Denied
2021-12-15T09:58:18+01:00 ✘
2021-12-15T09:58:18+01:00 ✘   ❌  Agc-Context-NextflowDemo-myuser4nFMjG-spotContext failed: Error: Failed to publish one or more assets. See the error messages above for more information.
2021-12-15T09:58:18+01:00 ✘      at Object.publishAssets (/Users/myuser/.agc/cdk/node_modules/aws-cdk/lib/util/asset-publishing.ts:25:11)
2021-12-15T09:58:18+01:00 ✘      at runMicrotasks (<anonymous>)
2021-12-15T09:58:18+01:00 ✘      at processTicksAndRejections (internal/process/task_queues.js:95:5)
2021-12-15T09:58:18+01:00 ✘      at Object.deployStack (/Users/myuser/.agc/cdk/node_modules/aws-cdk/lib/api/deploy-stack.ts:252:3)
2021-12-15T09:58:18+01:00 ✘      at CdkToolkit.deploy (/Users/myuser/.agc/cdk/node_modules/aws-cdk/lib/cdk-toolkit.ts:189:24)
2021-12-15T09:58:18+01:00 ✘      at initCommandLine (/Users/myuser/.agc/cdk/node_modules/aws-cdk/bin/cdk.ts:225:9)
2021-12-15T09:58:18+01:00 ✘  Failed to publish one or more assets. See the error messages above for more information.
2021-12-15T09:58:18+01:00 ✘  npm ERR! code ELIFECYCLE
2021-12-15T09:58:18+01:00 ✘  npm ERR! errno 1
2021-12-15T09:58:18+01:00 ✘  npm ERR! cdk@0.1.0 cdk: `cd $INIT_CWD && cdk "deploy" "--all" "--profile" "" "--require-approval" "never" "--output" "/Users/myuser/.agc/cdk/apps/context/cdk-output2281608007" "-c" "ENGINE_NAME=nextflow" "-c" "MAX_V_CPUS=256" "-c" "PROJECT=NextflowDemo" "-c" "OUTPUT_BUCKET=agc-1234567-us-east-1" "-c" "ADAPTER_DESIGNATION=" "-c" "READ_WRITE_BUCKET_ARNS=arn:aws:s3:::my-bucket" "-c" "USER_ID=myuser4nFMjG" "-c" "ENGINE_REPOSITORY=" "-c" "CONTEXT=spotContext" "-c" "BATCH_COMPUTE_INSTANCE_TYPES=c5,m5,r5" "-c" "ENGINE_HEALTH_CHECK_PATH=" "-c" "ADAPTER_NAME=" "-c" "ADAPTER_REPOSITORY=" "-c" "ARTIFACT_BUCKET=healthai-public-assets-us-east-1" "-c" "READ_BUCKET_ARNS=arn:aws:s3:::1000genomes" "-c" "REQUEST_SPOT_INSTANCES=true" "-c" "USER_EMAIL=myuser@amazon.com" "-c" "ENGINE_DESIGNATION=nextflow"`
2021-12-15T09:58:18+01:00 ✘  npm ERR! Exit status 1
2021-12-15T09:58:18+01:00 ✘  npm ERR!
2021-12-15T09:58:18+01:00 ✘  npm ERR! Failed at the cdk@0.1.0 cdk script.
2021-12-15T09:58:18+01:00 ✘  npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2021-12-15T09:58:18+01:00 ✘
2021-12-15T09:58:18+01:00 ✘  npm ERR! A complete log of this run can be found in:
2021-12-15T09:58:18+01:00 ✘  npm ERR!     /Users/myuser/.npm/_logs/2021-12-15T08_58_15_953Z-debug.log
2021-12-15T09:58:18+01:00 ✘  failed to deploy context 'onDemandContext' error="exit status 1"
2021-12-15T09:58:18+01:00 ✘  failed to deploy context 'spotContext' error="exit status 1"
2021-12-15T09:58:18+01:00 ✘   error="one or more contexts failed to deploy"
Error: an error occurred invoking 'context deploy'
with variables: {contexts:[] deployAll:true}
caused by: one or more contexts failed to deploy`
